### ISSUE TITLE
One question about bootasm.S

### ISSUE THREAD

**Issue by booniebears** [z4yx/assembly-naivemips#2]
在研读 bootasm.S的load_elf段时，观察到下面这一段代码，不是很明白:

      lui  $t0, 0xa000 #s4, p_va
      or   $s4, $s4, $t0 
    
    #copy from file_base+p_offset to p_va
    copy_sec:
      LOAD_WORD_R($t0, 0, $s6)
      sw $t0, 0($s4)
      addiu $s6, $s6, 4
      addiu $s4, $s4, 4
      addiu $s5, $s5, -4
      bgtz  $s5, copy_sec
      nop

lui  $t0, 0xa000和or   $s4, $s4, $t0相当于将p_vaddr与0xa000_0000或了一下，之后将Flash中的东西存到内存中。我对ELF相关知识不是很清楚。为什么要有这一步？是不能将Flash中的东西直接存到p_vaddr对应位置吗？感谢了

**Comment by z4yx** [comment]
ELF格式包含文件头和多个section，代码根据文件头，将ELF中的指令部分(.text段)复制到内存中。ELF格式描述可以查询相关资料，Linux里面有个readelf命令可以帮助你查看ELF文件头的信息。
